{
 "title": "Cowrie",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Unique Fingerprints",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(fingerprint)\nFROM keyfingerprints"
    }
   ]
  },
  {
   "title": "Inputs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  id\nFROM input\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Unique IPs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct ip)\nFROM sessions\nWHERE\n  $__timeFilter(starttime)\n"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id)\nFROM downloads\n"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(id)\nFROM clients\n"
    }
   ]
  },
  {
   "title": "Number of Auth Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  id\nFROM auth\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cowrie",
     "rawSql": "SELECT COUNT(input) AS input_count, input\nFROM cowrie.input\nGROUP BY input\nORDER BY input_count DESC\nLIMIT 50;\n"
    }
   ]
  },
  {
   "title": "Passwords tested",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cowrie",
     "rawSql": "SELECT COUNT(password) AS password_count, password\nFROM cowrie.auth\nGROUP BY password\nORDER BY password_count DESC\nLIMIT 50;"
    }
   ]
  }
 ]
}