version: "3"
services:
  cowrie:
    build:
        context: .
        dockerfile: ./docker/cowrie.Dockerfile
    image: cowrie
    # ports:
    #   - "22:22"
    #   - "23:23"
    #   - "2222:2222"
    #   - "2323:2323"


  db:
    build:
        context: .
        dockerfile: ./docker/db.Dockerfile
    restart: always # if something brokes, it will automatically restart
    image: db
    volumes:
      - cowrie-db:/var/lib/mysql:z
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=cowrie
      - MYSQL_USER=cowrie

  grafana:
    image: grafana/grafana:latest
    restart: always
    volumes:
      - grafana:/var/lib/grafana:z
    environment:
      # - GF_SERVER_DOMAIN=${SERVICE}
      # - GF_SERVER_ROOT_URL=https://${SERVICE}/
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_ANALYTICS_REPORTING_ENABLED=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=(`161.35.210.170`)"
      - "traefik.http.routers.django.entrypoints=websecure"
      - "traefik.http.routers.django.tls.certresolver=myresolver"
      - "traefik.http.services.django.loadbalancer.server.port=3000"
    ports:
      - "3000:3000"

volumes:
  cowrie-etc:
  cowrie-var:
  cowrie-db:
  grafana:


