name: Deploy

on:
  push:

jobs:
  release:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build & Tag Docker image
        run: |
          make up-prod
          docker tag cowrie ghcr.io/${{ github.repository }}/cowrie:latest
          docker tag db ghcr.io/${{ github.repository }}/db:latest
            
      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository }}/cowrie:latest
          docker push ghcr.io/${{ github.repository }}/db:latest